// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	handler2 "github.com/ljinf/im_server/internal/api/handler"
	server2 "github.com/ljinf/im_server/internal/api/server"
	service2 "github.com/ljinf/im_server/internal/api/service"
	"github.com/ljinf/im_server/internal/repository"
	repository2 "github.com/ljinf/im_server/internal/rpc/repository"
	"github.com/ljinf/im_server/pkg/app"
	"github.com/ljinf/im_server/pkg/jwt"
	"github.com/ljinf/im_server/pkg/log"
	"github.com/ljinf/im_server/pkg/server/http"
	"github.com/ljinf/im_server/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler2.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service2.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository2.NewUserRepository(repositoryRepository)
	userService := service2.NewUserService(serviceService, userRepository)
	userHandler := handler2.NewUserHandler(handlerHandler, userService)
	httpServer := server2.NewHTTPServer(logger, viperViper, jwtJWT, userHandler)
	job := server2.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository2.NewUserRepository)

var serviceSet = wire.NewSet(service2.NewService, service2.NewUserService)

var handlerSet = wire.NewSet(handler2.NewHandler, handler2.NewUserHandler)

var serverSet = wire.NewSet(server2.NewHTTPServer, server2.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server2.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
